### ISSUE TITLE
这个“机器人”主题的报告我们应该怎样写？

### ISSUE THREAD

**Issue by wangyin511** [AphroditeMM/I-Robot#1]
我们的目的是：

>如果你和我合作的话，我们选做第二个吧，可以把所学的知识再用一遍，而且，这个选题在信息搜索、信息整理、信息分析都有难度

我的想法是

结课作业最好能把课程的内容都过一遍，阳胖的课程围绕学术/商业/职业展开。我们也可以围绕这三点来设计报告内容，我们选择了机器人这个主题，一开始集中于机器人觉醒相关的文学艺术性作品（如pc游戏《底特律：化身为人》，而文学反应的是我们人类对机器的认知，这种认知除了体现在文学类，还可以体现在我们对人工智能的学术研究上，人工智能的职业内容上，公司投资人工智能的情况，除了课程的三个维度，我们自己设想的文学艺术作品类也是一个分析点。

有鉴于此：

报告的涉及内容：

报告从学术，商业，职业和文学艺术四个方面来展现当代人类对机器人或者说机器觉醒或者说人工智能等问题的理解认知和未来方向。从虚幻文学艺术作品到现实企业投资两个维度，来展现人类对机器觉醒的决心和恐惧。

问题1：我们是否限定主题，比如从机器人限定为机器觉醒或者人工智能，处于纯粹机械领域的不讨论，只分析那些带有智能倾向，有希望将机器造的和人一样的项目和作品。

报告可以拟定的题目：

1.人类的机器雄心与恐惧；2.创造辉煌的机器保姆和终结者；3.如果你的手机向你要自由与平等；4.机器觉醒前传（致敬2017年同名畅销书）。

问题2:报告的形式是图为主，文字辅之，还是文字为主，图辅之。

**Comment by AphroditeMM** [comment]
1. 赞同把研究方向扩展为：学术、商业、职业、文学。

其中，我认为在信息报告展示中，商业与职业部分息息相关，可以合为一部分。

 2. 对于问题1的回答：我个人倾向赞成「不对纯粹机械领域展开讨论」。

3. 信息报告展示形式：与认知写作课不同，这门课不采用keynote展示，我们以信息报告展示学习成果即可。文字与图表比例根据情况而定。
-  信息报告模板在实际撰写中确定即可。
