### ISSUE TITLE
再章：智能领域英才指南

### ISSUE THREAD

**Issue by wangyin511** [AphroditeMM/I-Robot#12]
> 3.再章：受了良好教育的少年，如果不读大学可以干什么？可以在人工智能行业哪些方向上创业？
> 
> 从商业信息看，最好的企业都在投人工智能哪些方向？他应该去哪些企业？做哪些项目？如果他要创业，该竞争哪些公司？从现有企业信息看，目前人工智能那个方向最火？小公司创业为避免竞争，应该如何选择方向？
> 
> 从空间的角度，哪些国外已经起来的技术，手段，公司而国内还没有的？也是创业的方向。
> 
> 拿自己举例，你我的人格特质，适合从事人工智能哪些工作，不适合哪些。或者我们假设一个青年的能力和性格，行业和背景，假如要从事相关行业，自我分析，如何设计转行计划？

**Comment by wangyin511** [comment]
1.onet上搜索和强人工智能相关岗位的职位列表，和需要的能力和性格特点。

2.主要人工智能公司企业创始人的性格特点，使用英才模型的分析。

**Comment by wangyin511** [comment]
底特律，有一个仿生人让人类大量失业的情节桥段，作为引子，引出那些行业未来会大量失业？

1.这里可以看美国的数据，大公司研究什么，现在的技术哪些是成熟的。

2.顺便提一下那些行业会坚挺。onet上这些职业的要求是什么？如何训练？

**Comment by wangyin511** [comment]
从目前独角兽企业的信息来看，哪个方向最火？中国哪些城市初创人工智能独角兽企业最多？北京和上海深圳的对比。人工智额相关的初创企业是那些？

国内还没有涉及和选择的方向是哪些？是否可以选择这些行业创业？这方面，盯紧美国的最新方向是不会错的选择。

**Comment by wangyin511** [comment]
你可以从那些学校找到适合的人才？几个重点学校的毕业生数量，国际国内。

**Comment by wangyin511** [comment]
腾讯人工智能人才白皮书

http://www.askci.com/news/finance/20171204/083817113211_2.shtml

**Comment by wangyin511** [comment]
全球人工智能发展报告
https://quqi.com/s/1/4AfsixSSCXlcgAZj

**Comment by wangyin511** [comment]
![v2-e3f8432b37a72992bf9d90e96ee52890_hd](https://user-images.githubusercontent.com/24407121/41883054-ece3c51a-791e-11e8-9ca9-ee2d08cebf78.jpg)

**Comment by wangyin511** [comment]
岗位：

https://www.jiqizhixin.com/articles/2018-01-27

**Comment by wangyin511** [comment]
事业情况：

https://www.jiqizhixin.com/articles/2018-01-27

**Comment by wangyin511** [comment]
https://www.glassdoor.com/index.htm

人工智能岗位信息

**Comment by AphroditeMM** [comment]
[波士顿咨询：中国已成为应用人工智能最积极的国家](http://www.199it.com/archives/740107.html)

侧面说明人工智能在中国的发展前景

**Comment by AphroditeMM** [comment]
[一份关于人工智能行业应用行业的报告](http://www.199it.com/archives/734259.html)

**Comment by AphroditeMM** [comment]
[一份预测人工智能是十大方向的报告](http://www.199it.com/archives/720703.html)

**Comment by AphroditeMM** [comment]
[一份关于人工智能深度学习的预测](http://www.199it.com/archives/714988.html)

**Comment by wangyin511** [comment]
思路修改，哪些职业被认为是很难替代的，这些职业未来的核心能力是哪些?

**Comment by wangyin511** [comment]
[唯人参之.pdf](https://github.com/AphroditeMM/I-Robot/files/2148797/default.pdf)
