### ISSUE TITLE
0624各章节合并：智能来袭应对指南

### ISSUE THREAD

**Issue by wangyin511** [AphroditeMM/I-Robot#14]
* 序章：人类如何看待人工智能

1. 2018年新出的轰动互动电影游戏《底特律：化身为人》：首周全球100万用户，大概故事介绍，仿生人觉醒自我意识，反抗人类。
2. 13个问卷，代表互联网游戏玩家对人工智能的直观认知。
3. 我们在看的，带有人工智能标签的电影是哪些？（搜狗视频，百度视频，豆瓣电影），各自评分前10的电影。这些除了人工智能以外的标签是哪些（战争？爱情？），几个重要的母题和假设，比如，物种冲突。最常见的英雄之旅。
4. 人类赋予没有生命的物体以生命的灵性，是一种隐喻本能。智能来袭最小故事模型：人类创造机器--机器反抗人类--人类打败机器或者机器求得平等。
5. 这个最小故事模型的反/元空是什么？

          反：人与机器和谐相处，机器压根没有觉醒。（或者觉醒了对人类没有威胁，比如和在人类现有社会体系下和人类发生爱情）。

          元：未来社会人类变成了机器，机器拯救人类恢复人性。

          空：智能是觉醒了，但把人类和机器放在同一个层次来看，人与机器都是智慧生物，能一起面对新的威胁和挑战。比如，另一伙外星人和我们作对，或者环境危机。

--------------------------------------------------

* 首章：人类研究人工智能的最高水准

1. 人工智能领域前30位大牛：Geoffrey Hinton；Lotfi A. Zadeh；Stephen Boyd；Michael I. Jordan；Terrence Sejnowski等，解决的核心问题是哪些？
2. zotero下载每位学者的论文，进行全局分析，标签等内容。重点时间段的成果数量变化原因。
3. 每位学者一篇代表作，快速审读给出核心论点信息。附加顶级期刊。
4. 人工智能重点实验室，和博士招生要求。国内高校：清华，中科院，北大，复旦，交通，港大，厦大。国外实验室：mit，斯坦福，卡尼吉梅隆，伯克利，布里斯托，希伯来，牛津，Dalle Molle，sciai，苏黎世。重点实验室的获奖学生名单。课程信息情况。国内重点高校考试题目情况，国外实验室申请要求。
5. 知识图谱展示地理位置（使用现成的报告结果还是自己做？现成报告简单一些，自己做能锻炼～）

---------------------------------------------------------

* 次章：智能来袭，下一代应该怎样学习？（这章会稍微偏离一下主题，但文字上可以融回来，主要是我的兴趣点在这，求体谅）

1. 我们对人工智能的焦虑和人类每个时代的焦虑一致，都是对不确定性的焦虑。人类社会历史上的重要改革节点，人们的焦虑重现。
2. 接上，当代中国的教育焦虑，阐述最适合国人教育的对标国家是日本。
3. 讲一个日本小学生的思维能力进阶的故事。日本教育巨头倍乐生公司的终身教育体系介绍，使用价值链分析法/利润模式分析法研究倍乐生。舆情分析。再讲一个美国小学生的故事，对比他们的能力成长故事。
4. 国内儿童教育独角兽分析（这里就不分细节了，避免和阳老师的冲突，但是阳老师的报告框架我看了，缺少整体分析，我们分析整体），数据库来源=it桔子、新三板、A股。时间/空间分布。
     5.社会工程分析法：假装是孩子家长给教机器人编程的儿童公司打电话，获取信息。

-------------------------------------------------

* 再章：智能领域英才指南

1. onet上搜索和强人工智能相关岗位的职位列表，和需要的能力和性格特点。
2. 主要人工智能独角兽公司企业创始人的性格特点，使用英才模型的分析。顺着独角兽企业名单。
3. 未来有可能会失业的领域，或者随着人工智能技术成熟，裁员率会开始飙升的行业。对标美国社会。
4. 但是哪些职业会坚挺，onet上的职业要求是什么？哪些反常识的点？比如作家。
5. 如果要创业，国内英才可以选择哪些方向？对标美国最近两年起来的独角兽名单和方向，最为国内参考。
6. 如果要在国内的学校找毕业生给你干活，有哪几个学校可供选择？毕业生都是什么层次的？公司创始人和学校相互关系的网络分析。

---------------------------------------------------------------

* 终章：觉醒前夜，超越梦想和回归现实

超越梦想：

1. 最近三年开始的人工智能领域重大突破：未来可能涉及的场景。一项论文或者技术--------》未来有可能突破的实际场景----------------》从事这项工作的人，列举10个。可以串联前几章，技术/场景/母题/人。
2. 人工智能的东方哲学伦理的可能性，牟宗三，熊十力。

回归现实：

1. 如果以上假设是错误的，我们当下理解的人类大脑和思维方式是如何的？
2. 人脑的计算力，认知能力等远高于计算机能力。目前计算机可以达到的水平，目前对人类大脑研究的已知程度。
3. 把从机器的重点回归到人，人应该注重那些能力？除了人工智能以外，还有哪些我们应该关注的领域？

------------------------------------------------------

* 附录：

1. 哪些书？
2. 哪些报告？
3. 哪些企业？
4. 哪些论文？
5. 哪些数据？

**Comment by wangyin511** [comment]
这几天我把我的思路理顺了，你看看有木有补充，每一章的卡片材料我都单独开了issue，每章素材不断往里面放，剩下的就是往里面填了～ @AphroditeMM

**Comment by wangyin511** [comment]
晚上我吃完小龙虾回来，再就着这个写一点，再过一天应该能出1.0版本

**Comment by wangyin511** [comment]
1、未来三年到五年，整个儿童教育行业的趋势；
2、未来三年到五年，最有前景的细分行业；
3、未来三年到五年，最值得投资的细分行业的龙头公司。

--------------------------------------------------------------------------------

要得出这三项结论，像阳老师给点的方法那样分析每一个细分行业是很难得出结论的，应该对独角兽教育公司进行总体综合分析对比，才能得出这些结论。

**Comment by wangyin511** [comment]
中国信通院产业报告

http://www.caict.ac.cn/kxyj/qwfb/ztbg/

**Comment by AphroditeMM** [comment]
序章1.0版本我放到了仓库，点击跳转：
[人类眼中的人工智能](https://github.com/AphroditeMM/I-Robot/blob/master/%E5%BA%8F%E7%AB%A0.md)

----
版本1.0有以下问题：
1. 需更改问卷呈现形式，现在的太丑了；
2. 爱文同学看下逻辑通不通，有异议请沟通；
3. 影视清单的分析草稿，我放了一份excel在仓库，地址跳转[影视作品清单是这样出来的](https://github.com/AphroditeMM/I-Robot/blob/master/%E5%BD%B1%E8%A7%86%E5%88%86%E6%9E%90%E6%B8%85%E5%8D%95%E5%88%86%E6%9E%90%E8%BF%87%E7%A8%8B%E8%8D%89%E7%A8%BF.xlsx)

**Comment by wangyin511** [comment]
增加一个信息点；从数据上看，我即认为科技的发展会对人类产生威胁，我们同样也希望能和仿生人发生亲密关系，希望他们帮人类养育孩子，矛盾也。 @AphroditeMM

**Comment by AphroditeMM** [comment]
再章1.0版本滚烫出炉，见阅[再章](https://github.com/AphroditeMM/I-Robot/blob/master/%E5%86%8D%E7%AB%A0.md)

温馨提示：图片很多，网速慢的话请耐心等待加载完毕。

-----
松口气。不过怎么感觉工作才完成三分之一，还有三分之二的工作在后面等着……

加油加油~~

**Comment by wangyin511** [comment]
@AphroditeMM 有一个挺重要的趋势，就是小样本学习。这是和机器学习相对的趋势，即不需要数据喂养，从个案中获取信息点，做出判断。

https://www.jiqizhixin.com/articles/2018-06-20-13

one shot learning，小样本学习最新进展

这个我们晚上一起探讨，看看以怎样的形式放进去分析。

**Comment by wangyin511** [comment]
再章：[唯人参之.pdf](https://github.com/AphroditeMM/I-Robot/files/2148800/default.pdf)

**Comment by wangyin511** [comment]
终章：
[终章：蓦然回首.pdf](https://github.com/AphroditeMM/I-Robot/files/2148812/default.pdf)

**Comment by wangyin511** [comment]
[次章：鹅湖之会.pdf](https://github.com/AphroditeMM/I-Robot/files/2148825/default.pdf)

**Comment by wanyiping** [comment]
这篇文章信息量挺大，使用了信息分析课的很多技法，给读者带来不少新知识。好的方面就不多说了，谈几点疑问。

- 序章中"人类如何看待智能觉醒"，这个问题与"智能时代的应对指南"的逻辑关系是什么？另外，只统计游戏用户，是否会产生明显的取样偏差？

- 序章讲"智能觉醒"，这和智能时代是同一个问题吗？也就是说，智能时代可能没有"觉醒"，但同样带来了生活方式的巨大变化。

- 第一章总体问题不大，最后一节"未来的研究方向"是如何得出来的？这个其实不用猜，目前顶级实验室和顶级会议的研究方向就是未来的研究方向。

- 第一章还缺了一部分，就是互联网（科技）公司在智能产品方面的布局。产业界比学术界更直接地影响普通大众－－我们在智能时代应对的，是产品，而不是学术研究。

- 第二章"教育行业"与"应对指南"的关系是什么？为什么要有这一章？

- 未来不容易被替代的职业，作者是如何分析出来的？这一点显得很薄弱。

- 终章方面，最后是否可以提供一个建议清单？（最好是实践策略清单）这才称得上是应对指南。信息分析报告里完全可以不出现哲学和伦理学讨论，但不能缺少关键性的判断和建议。

以上是我的一些疑问，欢迎批评讨论。
