### ISSUE TITLE
目录页：标题汇总（解决我们这个分析了什么问题）

### ISSUE THREAD

**Issue by wangyin511** [AphroditeMM/I-Robot#18]
智能时代应对指南

* 序章：有心之器

1. 人类是如何看待智能觉醒的？
2. 智能觉醒的故事母题有哪些？
3. 我们是怎么分析这些电影的？
4. 送你一份智能觉醒相关影视作品清单

* 第一章：沙滩手表

1. 人工智能领域有哪些大牛？
2. 这些大牛都在研究哪些方向？
3. 重要论文都去哪里寻找？
4. 偷偷告诉你人工智能的下一个方向是什么

* 第二章：鹅湖之会

1. 如果你要在中国创立一家最好的教育公司，你该向谁学习？
2. 如何分析你的学习榜样，去哪里分析你的榜样？
3. 教育产品的好细节有哪些？
4. 分享一个我们在教育行业的创业构想

* 第三章：唯人参之

1.未来哪些职业不会被机器人替代？
2.这些职业有哪些核心能力？
3.我们能从全球独角兽企业的基本信息中看出什么？
4.请您验证一个假设

* 终章：无限游戏

1.如何联想人工智能相关技术的未来场景？
2.至今以来的人类哲学成果对机器觉醒有什么启发？
3.东方哲学在智能伦理领域的优势何在？
4.回到现实中来，请关注人的思维本质

--------------------------

@AphroditeMM 这是你一开始这个报告说了什么内容的框架报告，你制作封面页页可以用到，请注意终章的标题改了。但是这也仅作为目录标题使用，每个章节内部具体的划分还是不这样来，按照之前行文的特点具体分开。

**Comment by AphroditeMM** [comment]
整合版本我放在仓库里，参见链接[智能时代应对指南](https://github.com/AphroditeMM/I-Robot/blob/master/%E6%99%BA%E8%83%BD%E6%97%B6%E4%BB%A3%E5%BA%94%E5%AF%B9%E6%8C%87%E5%8D%97.md)

---
1.0版本整合情况介绍：

1. 添加简单的串联词把各章内容整合。
2. 把已有增补内容填入对应章节，尚未增补内容情况：
---

第一章
缺：
>@AphroditeMM 我来整理学术内容，你看看能不能从学术数据或知识图谱那边得出小样本比较重要的结论。

缺：
沙滩手表的释义。

第二章

倍乐生雇员情况为什么不给截图？
财报解读还要提供吗？

没有增补
巧虎的新榜指数

第三章 
不可被取代的职业介绍内容实在太多了，得想个更好的办法呈现

终章
终章内容我丝毫没有动，对于我来说，有些难理解，听取第三方一件后回头再看看。

**Comment by wangyin511** [comment]
巧虎新榜指数

从新榜的数据来看，巧虎乐智小天地的活跃粉丝数为264368，近几日新榜指数为721-680。尽管新榜的数据由于算法原因和实际情况有所出入，但是同平台内横向对比还是具有可比性的。我们对比同是拥有育儿标签的爱贝睿公司公号（新榜指数为635），活跃粉丝数量为33456。新榜中带有育儿母婴类标签的公号中，新榜指数前两位的公号是爸妈营和丁香妈妈，活跃粉丝数量分别为581167和946015。

从数据上看，巧虎的公号粉丝基数位于行业内中上游水平，但是相比行业上游其他公号，数据浮动变化更大，更新频率更低，但是单次文章更新使得当天名次变动极大（200-700浮动），说明于行业内有较高影响力。

从近几日发文数据看，单篇单次阅读量数据爸妈营大致是43484篇，巧虎为17053篇，爱贝睿为2802篇。我们试想，有可能新榜的数据算法不一定符合实际情况，但是只要算法是统一的，统一算法下不同公号依然有可比性。

巧虎更新速率明显低于其他公号（最近6日，6月24日-30日仅为4篇，爸妈营为56篇，爱贝睿为14篇）但是公号单篇单次阅读数据处于行业中上游，我们判断这一品牌对行业的影响较实际数据为大。

**Comment by wangyin511** [comment]
> 我们能否创立一个平台体系，整合全国「素质教育」培训信息呢？

我们能否创立一个平台，改变现有艺术类培训（戏剧，绘画，音乐，雕塑等）过于依赖老师个人作坊式的培训体系，建立全国系统化的，整合教师资源的，带有评估体系的培训平台呢？

**Comment by wangyin511** [comment]
@AphroditeMM 

1.你需要删除一些我们讨论后不需要的东西，比如终章中的技术设想

2.每一章布置一个小任务，第三章那个小任务说的多一点。

3.部分文字细节下次语音沟通~辛苦了哈~

4.第三章部分独角兽企业部分，章节小标题按照讨论直接使用结论

5.沙滩手表

**Comment by wangyin511** [comment]
我明天继续增补，倍乐生的财报信息。

**Comment by wangyin511** [comment]
> 为机器立心也并非只有西方路径，特别是牟宗三先生的研究，打通了陆王心学，心灵哲学和当代科学，提出道统，学统和政统

终章这部分文字，其中的当代科学应该改为“现代科学”。

这个改动很重要，要不然是硬伤。 @AphroditeMM 

-------------------------------------------------------------------------

还有一个要调整的：

最终此段调整为：

为机器立心也并非只有西方路径，特别是牟宗三先生的研究，梳理了中西哲学的脉络，提出道统，学统和政统。相信这种道德本体的哲学能汇通陆王心学，心灵哲学和当代科学，也能让人类为机器立心。（这一观点来自蔡恒进; 蔡天琪; 张文蔚; 汪恺. 《机器崛起前传——自我意识与人类智慧的开端》）

**Comment by wangyin511** [comment]
> 如果我们对涉及机器人伦理的论文进行整合整理，具体列表见zotero组群

我们对涉及机器人伦理的论文进行整理，具体列表见附表。

**Comment by AphroditeMM** [comment]
@wangyin511 上面说的我已经修改了，见文章[智能时代应对指南](https://github.com/AphroditeMM/I-Robot/blob/master/%E6%99%BA%E8%83%BD%E6%97%B6%E4%BB%A3%E5%BA%94%E5%AF%B9%E6%8C%87%E5%8D%97.md)

有一点我觉得还要再商榷：
我现在看来章节小任务会不会有些奇怪，以什么语气来说？认为任务还要再商榷。

**Comment by AphroditeMM** [comment]
@wangyin511 我把昨晚语聊的修改提交了，并且改了一遍错别。快速[报告传送门](https://github.com/AphroditeMM/I-Robot/blob/master/%E6%99%BA%E8%83%BD%E6%97%B6%E4%BB%A3%E5%BA%94%E5%AF%B9%E6%8C%87%E5%8D%97.md)

**Comment by wangyin511** [comment]
小样本组群：https://www.zotero.org/groups/2202377/one_shot_learning?
