### ISSUE TITLE
学术上，机器觉醒这个主题怎么分析？

### ISSUE THREAD

**Issue by wangyin511** [AphroditeMM/I-Robot#2]
立足全局分析，以人工智能为主题进行搜索，整理主要人物的主要论点。集中于人工智能哲学？还是全部都关注？或者看看学术上智能机器立足于模仿人类的哪些能力？当下集中解决哪些问题？

**Comment by AphroditeMM** [comment]
这个观点把我之前的「文学艺术上机器人主题」的想法进行扩展，延伸至「人工智能领域」。我试想了一下关于「人工智能」学术上研究，有什么与我们项目有关系。

实践策略方向：
1. 「人工智能」研究历史脉络；
2. 「人工智能」研究最新进展（典型案例是alpha战胜围棋冠军）
3. 「人工智能」领域大牛；代表企业等。

我们从学术角度研究人工智能，目的在：1. 展示人类对「人工智能」的态度、研究成果 ；2. 预测人工智能的未来走向。

因此，你的「问号」似乎都可以成为我们报告中学术部分的副标题。
