### ISSUE TITLE
职业上，如何看待从事“机器觉醒”-人工智能行业

### ISSUE THREAD

**Issue by wangyin511** [AphroditeMM/I-Robot#3]
1.相关工作的任职能力和场景。未来趋势如何？如果有孩子有志于此，要未雨绸缪学习，应该学习哪些？注重哪些能力？重要国家对此付出哪些努力。

2.机器觉醒相关小说家，游戏项目工作人员的薪酬水准。网络机器觉醒相关重要投票结果，大家的意向如何？

3.机器人相关文学作品/电影/游戏的热度等。

**Comment by AphroditeMM** [comment]
我认为商业这部分可以有两个方向开展：
- 商业
借助影响力大的互联网公司（西方：谷歌、微软；东方：腾讯等）投资清单，看「人工智能」发展方向。

- 职业
 借助Onet系统、招聘网站等，检索相关职业与前景。（这部分内容以图表展示为佳）
 举例职业：1、工程师；2、游戏；3、作家
