### ISSUE TITLE
商业上，机器觉醒的未来方向在哪里？

### ISSUE THREAD

**Issue by wangyin511** [AphroditeMM/I-Robot#4]
1.大公司针对人工智能的投资情况，未来方向是哪些？人类社会生活有哪些会被机器替代？还有哪些没有被替代，可能的原因是哪些？攻克的难点在哪里？

2.行业内对机器觉醒做了现实的哪些准备？截止2018年现在为止，我们对机器人行为伦理问题的认知。

3.机器未来的模样如何？

**Comment by AphroditeMM** [comment]
>1.大公司针对人工智能的投资情况，未来方向是哪些？人类社会生活有哪些会被机器替代？还有哪些没有被替代，可能的原因是哪些？攻克的难点在哪里？

哈哈，感觉这部分内容好难找。因为必须深入到从事「人工智能」行业才会获得答案。

2. 伦理问题是个一个有趣的角度，但它更应该划分在学术研究领域？

3. 机器未来的模样，可以从文学作品上获得答案。
