### ISSUE TITLE
文学艺术上，我们使用的机器觉醒母题是什么？

### ISSUE THREAD

**Issue by wangyin511** [AphroditeMM/I-Robot#5]
1.为什么我一直希望机器会有自己的意识？我们一开始就假定机器一定会觉醒，人类自己的哪些认知或者隐喻影响了我们这个先天的认定。

2.我们害怕机器的哪些方面？这里使用重要作品桥段来说明。

3.机器觉醒的最小故事。

4.如何创建一个新颖的机器觉醒题材？机器觉醒的新篇章可以是哪些？结合时空变形的理论。

**Comment by AphroditeMM** [comment]
得出「母题」结论需要建立文本分析上，我估计从「科幻小说」中就可以得出答案，然后可以拿「电影」与「游戏」作品交叉验证。

这里我们需要拿出样本研究清单。你我可以各列一个清单，再进行对比（清单上两人都有的，留下；没有的讨论去留）。
