### ISSUE TITLE
提纲讨论-----机器觉醒前夜，我们应该做什么？

### ISSUE THREAD

**Issue by wangyin511** [AphroditeMM/I-Robot#6]
机器觉醒前夜：我们应该做些什么？

（报告提纲框架）开篇陈述报告要解决的问题：信息分析的核心目的就是为了应对不确定性，我们应该如何理解机器觉醒这个主题？我们当下可以做些什么？

一、我们如何看待机器觉醒？
再从2008年开始至今10年，每年影响力最大的涉及机器觉醒的年度代表作（电影或者游戏），以票房或者销售量为最简单的限定标准，其中涉及机器反抗人类的数量比例。

我们从中总结出最小故事模型，和角色的英雄之旅，这就代表了我们至今为止看待机器的最泛用的认知模式。给一个具体的例子，2018年最新的游戏《底特律：化身为人》，问卷的选择，显示了我们对机器人觉醒的大众认知。

最小故事模型：人类创造机器--2.机器反抗人类--3.人类打败机器或者机器求得平等。

主题点：自由，爱情，温馨和人类的傲慢等。

反常识的点：文学求新，这里利用反元空模型，我们给出新的故事或者游戏框架。

反：人与机器和谐相处，机器压根没有觉醒。（或者觉醒了对人类没有威胁，比如和在人类现有社会体系下和人类发生爱情）

元：机器是觉醒了，把人类和机器放在同一个层次来看，人与机器都是智慧生物，能一起面对新的威胁和挑战。比如，另一伙外星人和我们作对，或者环境危机。

空：未来社会人类变成了机器，机器拯救人类恢复人性。

二、我们如何研究人工智能?先罗列一些基本数据，比如每年研究此类论文的增长趋势，全局分析下zotero的标签有哪些等等。

随后回答几个问题：1.世界有哪些重要的实验室在做人工智能研究？2.哪些顶尖学者，google排名？3.如果每年选择一篇人工智能领域最杰出的代表作，那么2008年-现在，按照时间线而言，我们认为最重要的10篇论文是哪些？表现出了哪些研究的趋势？4.人工智能研究有哪些分支？5.哪些曾经被认为很重要的论点最后被打脸舍弃了。

信息展示要点：1.知识图谱；2.最小知识(核心话语体系、核心知识体系、发展脉络、其他学科如何看待本学科）；3.历史源头和关键点：简单提一下西蒙那个时代----韩丁-----现在。

还有哪些领域没有被涉及，学术上我们应该如何探索？（这个在相关论文一般结尾都会有，找几篇2018年或者2017年的论文交叉验证取最大公约数展示）人工智能领域知识的转折点有可能是哪些？（ch1知识点-陈超美转折点理论，联结两个不相关的领域）机器人伦理，人工智能哲学补充。

反常识：

三、我们如何使用人工智能？

商业上人工智能的应用场景：无人驾驶、教育、金融等。利用现有分析报告，交叉验证，获取信息。

人工智能研究重镇的投资方向：国外google，facebook；国内：腾讯，百度，财报相关方向对比。小企业的人工智能研究方向，其他行业如何对接这一趋势。

行业主要5大主要工种所需技能，如ai产品经理、人工智能数据分析等，算法工程师等，利用onet现成材料数据和薪酬情况。

如果我们要进入这个行业，未来有哪些工种可供选择？

反常识的点：目前认为人工智能最难进入的领域是哪些，有哪些手段突破？我们突破后带来哪些价值？

四、我们如何学习人工智能？

如果你是青年，要从零开始，应该如何了解人工智能？第一步，现有的ted演讲，整理出来成列；第二步，涉及入门书籍，呈列；第三步，科学家排名呈列，部分论文展示；

反常识的点：1.传统上我们以为学习人工智能需要专业学习，实际上这是一个变动的领域，学经典不如啃前沿。

如果你想教育青少年，要从零开始学习人工智能？需要掌握哪些技巧手段？这一点需要收集材料去呈列。

目前教育培训届针对孩子的人工智能教育在哪些方面？

反常识：太小的孩子接触机器不好，但是未来孩子需要大量接触设备，如何正确引导？（爱贝睿应该有相应文章讲解，可以学习参考）

五、如果以上都是错的

有没有可能人工智能机器觉醒是伪命题？以上假设都是错的，只是我们人类太寂寞，如果机器觉醒是错的，永远不可能有自主意识，只是我们的想象力副产品。我们人类能不能机器化？

我们只想到了机器的人类化，我们人类也能机器化，谁来拯救人类？

我们拥有人类的大脑，机械的身体是否可能？

**Comment by wangyin511** [comment]
@AphroditeMM

**Comment by AphroditeMM** [comment]
给一个具体的例子，2018年最新的游戏《底特律：化身为人》，问卷的选择，显示了我们对机器人觉醒的大众认知。
——————
这里呈现「大众对机器人的态度」：我们拿你手头上的《底特律》问卷数据分析即可，不需延伸，使用图表呈现。

**Comment by AphroditeMM** [comment]
给一个具体的例子，2018年最新的游戏《底特律：化身为人》，问卷的选择，显示了我们对机器人觉醒的大众认知。
——————
这里呈现「大众对机器人的态度」：我们拿你手头上的《底特律》问卷分析即可，不需延伸，使用图表呈现。

**Comment by AphroditeMM** [comment]
[中国知网| 人工智能 研究热度统计](http://kns.cnki.net/kns/brief/Default_Result.aspx?code=CIDX&kw=%E7%A4%BE%E4%BA%A4%E7%BD%91%E7%BB%9C&korder=&sel=1)

在中国知网以「人工智能」为搜索词，点击「指数」标签，有关注度统计。

一些数据蛮有意思：

1. 在人工智能研究上，外国文献数量浮浮沉沉，有几个节点呈现超100%的增长：1935、1980、2010。
我们重点关注2010年发生了什么事？有哪些论文发表了？有什么新的研究进展？（私估计是深度学习理论提出）
2. 在人工智能研究领域上，中国文献数量呈持续递增趋势，1994年开始增速。尤其是2014-2017年，论文发表数量呈指数级增长（2017年发表的论文多达9092篇）。可见人工智能在中国近五年热度「炙手可热」啊。
3. 相关词给出。人们在谈人工智能时，有可能在指「机器人、学习、计算机视觉、专家系统、神经网络」。
4. 中国人工智能领域研究前五高校：上海交大、哈尔滨工业、清华、浙大、北航。

**Comment by wangyin511** [comment]
目前暂定的提纲，一小时读懂人工智能报告

---------------------------

0.序章：我们如何看待人工智能

底特律的10个问卷，今天最新最好的游戏电影是如何看待人工智能的，历史上的相关作品有哪些，我们可以总结的母题有哪些（比如，物种冲突，人类移情，支持这些母题的）。

这些母题的反元空是哪些？哪几种类型的母题或者题材结合在“机器觉醒”还没有作品存在，而可以去一写的？

既然现在趋势如此，我一个文科生如何和人工智能结合在一起？

1.首章：一个文科生如何和人工智能联系在一起？如何学习人工智能？

文科生学习人工智能的途径有哪些，方法有哪些，有哪些好的机构和公司可以去，这些领域有哪些成果哪些人？（42位大牛和简介）文科生怎么学（能力如何进阶，人工智能学生的课程设计，目前干人工智能的人的性格特点），读哪些核心论文？（按领域年度代表作，从08年开始列10篇）。

人工智能博士招生的方向有哪些？培养的计划是怎样的？

2次章：我们的下一代如何学习人工智能？

从上一个话题可以推出这个话题，青年的教育是一种弥补，那么儿童教育如何与「人工智能」发生关系？如何未雨绸缪？

国内最好的人工智能或者说机器人培训机构是哪些？这里有个课程没有提到，但是《社会工程学》提到的策略，比如可以假装是孩子家长给机构打电话要材料，看看是如何培训的，国外机构是如何培训，最好的私立学校这方面课程是如何设置的。但是未来所有孩子都需要学人工智能吗？机器无法替代的有哪些领域？

假设你的孩子按照现有的信息量，学了人工智能的相关知识，现在长大了，不想读大学，假如他要在这个领域出人头地，有哪些途径？

3.再章：学习了人工智能领域知识的少年，如果不读大学可以干什么？

从商业信息看，最好的企业都在投人工智能哪些方向？他应该去哪些企业？做哪些项目？如果他要创业，该竞争哪些公司？从现有企业信息看，目前人工智能那个方向最火？小公司创业为避免竞争，应该如何选择方向？

从空间的角度，哪些国外已经起来的技术，手段，公司而国内还没有的？也是创业的方向。

拿自己举例，你我的人格特质，适合从事人工智能哪些工作，不适合哪些。或者我们假设一个青年的能力和性格，行业和背景，假如要从事相关行业，自我分析，如何设计转行计划？

4.末章：觉醒前夜

结合上述章节中出现的信息，对近10年的机器觉醒领域做场景的预测：比如从娱乐角度，目前还没有涉及的机器觉醒类母题是哪些？以后有可能会成功的故事点；从生活角度，哪些还没有被涉及的行业或者领域，一旦某个在研的领域有所突破，会带来怎样的改变？

从时间差的角度，学术到商业通常都需要时间来迭代，课程中说是7-8年，我们看2017年或者18年的重点突破，来预测未来的可能方向。比如，从大数据模型走向机器从个案获取信息作出决策。

一项论文或者技术--------》未来有可能突破的实际场景----------------》从事这项工作的人，列举10个，串联前三章。

**Comment by wangyin511** [comment]
思想实验，符号思考，实验科学，计算模拟，田野调查，多元认知。

----------------

序章：思想实验，符号思考

首章：实验科学，计算模拟

次章：田野调查，多元认知

再章：符号思考，计算模拟

终章：多元认知，思想实验

**Comment by AphroditeMM** [comment]
>1.首章：一个文科生如何和人工智能联系在一起？如何学习人工智能？

>文科生学习人工智能的途径有哪些，方法有哪些，有哪些好的机构和公司可以去，这些领域有哪些成果哪些人？（42位大牛和简介）文科生怎么学（能力如何进阶，人工智能学生的课程设计，目前干人工智能的人的性格特点），读哪些核心论文？（按领域年度代表作，从08年开始列10篇）。

------

这个以文科生为切入点代表性不足。我认为不用强调文科生/理科生。

**Comment by AphroditeMM** [comment]
>2次章：我们的下一代如何学习人工智能？

>从上一个话题可以推出这个话题，青年的教育是一种弥补，那么儿童教育如何与「人工智能」发生关系？如何未雨绸缪？

>国内最好的人工智能或者说机器人培训机构是哪些？这里有个课程没有提到，但是《社会工程学》提到的策略，比如可以假装是孩子家长给机构打电话要材料，看看是如何培训的，国外机构是如何培训，最好的私立学校这方面课程是如何设置的。但是未来所有孩子都需要学人工智能吗？机器无法替代的有哪些领域？

>假设你的孩子按照现有的信息量，学了人工智能的相关知识，现在长大了，不想读大学，假如他要在这个领域出人头地，有哪些途径？

-----
读了上面的话，我理解，次章的重点围绕「儿童教育」，或者换句话说，「人工智能教育」从娃娃捉起。我们的聚焦点肯定是在中国吧。思路该是，中国儿童教育与人工智能相关的现状如何？（假如有不足，我们列举外国例子给予建议）

----
>1.但是未来所有孩子都需要学人工智能吗？2.机器无法替代的有哪些领域？

----
1.问也太「技术乐观」了吧，不用数据调查都知道，（现实地说）不是所有人都需要学人工智能啊。
2.我们在数据之上应该有个未来预测，但2问以你我局外人身份来看，很难回答。
