### ISSUE TITLE
线下沟通后，想到一些问题

### ISSUE THREAD

**Issue by AphroditeMM** [AphroditeMM/I-Robot#8]
混乱的记录：

我：
我们在「人工智能」或者说「机器人」话题中，最感兴趣的是什么？我们要验证怎样的结论？

你：
1.差距，就是文学中的设想和学术现实中的差距。
2.机器人故事的隐喻母题，和超越这个母题的其他故事可能性。
3.从商业信息判断，机器觉醒是否是未来真的趋势，这个可以和今天阳老师说的大公司投资策略结合。
4.如果趋势为真，儿童应该怎样教育适应这个趋势，这些是我在提纲里列的，也比较有兴趣的点。

———
因此我是否可以理解为：1、2、3点搜索信息的行为是为点4服务的。我们报告最终注脚是：儿童教育如何与「人工智能」发生关系？提出建议。

我：
在这个话题里，我最初的出发点是「验证科幻小说中的机器人主题，是否可以上升到物种冲突这个故事模型中」。后来，你提出把研究扩展到「人工智能」，我觉得也不错，于是会想知道，「我一个文科生怎样跟最有前景的人工智能发生关系」？

——「我一个文科生怎样跟最有前景的人工智能发生关系」——这是一个很有现实意义的问题，但这个问题具有普遍意义吗？同问：「儿童教育如何与人工智能发生关系」，这个问题具有普遍意义吗？

————
如果从「文科生或儿童教育怎样跟人工智能发生关系」问题出发，我们需要回答：人工智能是未来最有前景的职业，因此有点3的商业判断；接着，或许我们会想知道，「人们在聊人工智能时，在聊什么？」，于是我们有学术上的探讨。

———

我在线下跟小伙伴讨论「人工智能」，他提出一个讽喻：当今蹭「人工智能」有三种典型话题：冰山上聊阿法狗、水面下「神经网络」，底层话题才是真正的「人工智能」。

我们需要挖掘「人工智能」的本质。

——

你：
这里有两种思路：一种是成为设计机器的人；一种是成为机器无法取代的人。把现有职位按这两种可替代性程度区分，就能初步得出结论。

——

很明显，你这个想法，是仅仅站在「商业角度」来谈，但是我们需要才能够整个分析报告的层面来看思路。

——
我：
我觉得，是否要围绕一个点，构建我们的行为：学术要做什么、商业上要做什么，这些行为都是为了这个核心点而做的。行为完成后，我们验证结论，在结论基础上再上升到普世价值。所以，我一直在问，我们研究的最最核心点是什么？

你：
我一开始也从核心点出发思考，但是想不到特别好的，就用了这个框架曲线救国，但是你说的对，每一个领域提一个核心点。

你：
学术上：人工智能是基于深度学习大数据还是个案结论人类思维模式？
商业上：人工智能各个方向目前哪个维度是100亿级别企业投资重点。
文学上：人与机器的故事母题和反元空是什么？

----

阳老师说最好关联的数据库不要超过4个，跨2个领域为佳。框架上，我们设计学术、商业、职业、文学四个，太多了，必须要舍弃或者有详略。（无论领域还是策略都需要有内在逻辑关联）

——
我们再从实践策略来看，我们要刻意练习哪些策略？

——

报告形式：这个应该是最没有分歧点，信息分析报告。不采用keynote形式。

小结：

1. 人们在聊人工智能时，在聊什么？
2. 我们刻意训练什么实践策略？
3. 我们报告的现实意义是什么？是为读者（开智学友们）感兴趣而写？还是为你我的兴趣而做？
4. 我们报告的结论核心论点是什么？

——
行动：
1. 规划时间节点

----
20180620

上面记录快记于当年线下聚会结束后，之前没有发出来，是因为觉得自己尚未建立一个清晰框架的概念。
1. 我们发散的点很多，我依然不清楚我们要研究什么？
2. 先丢出把各自的搜索结果，从中选择研究点，思路一；
3. 我按照你之前写的大纲做了一些搜索之后，发现你提到的点确实是重温课程实践技巧的好提醒。（笑）

----
加油，有问题随时沟通

**Comment by wangyin511** [comment]
你说的挺好，报告可以顺便把学友们的兴趣点解决。这份报告除了信息分析的写法，适当增加文学性也未尝不可，把写作课的技巧也用上，毕竟都是可以自己调整的，没有必要完全按照课程给定的来。

看了你的分析，我的想法是，这份信息分析报告可以采取问题解决的形式，我之前过于纠结于课程和阳老师给我们的领域，我们纠结于学术、商业和文学等，但是我们换个思路用问题解决的思路看看，因为所谓商业，学术和职业分析都是手段而已，比如你个人的困惑完全可以是一个公共的话题。

0.序章：我们如何看待人工智能

底特律的10个问卷，今天最新最好的游戏电影是如何看待人工智能的，历史上的相关作品有哪些，我们可以总结的母题有哪些（比如，物种冲突，人类移情，支持这些母题的）。

这些母题的反元空是哪些？哪几种类型的母题或者题材结合在“机器觉醒”还没有作品存在，而可以去一写的？

既然现在趋势如此，我一个文科生如何和人工智能结合在一起？

1.首章：一个文科生如何和人工智能联系在一起？如何学习人工智能？

文科生学习人工智能的途径有哪些，方法有哪些，有哪些好的机构和公司可以去，这些领域有哪些成果哪些人？（42位大牛和简介）文科生怎么学（能力如何进阶，人工智能学生的课程设计，目前干人工智能的人的性格特点），读哪些核心论文？（按领域年度代表作，从08年开始列10篇）。

人工智能博士招生的方向有哪些？培养的计划是怎样的？

2次章：我们的下一代如何学习人工智能？

从上一个话题可以推出这个话题，青年的教育是一种弥补，那么儿童教育如何与「人工智能」发生关系？如何未雨绸缪？

国内最好的人工智能或者说机器人培训机构是哪些？这里有个课程没有提到，但是《社会工程学》提到的策略，比如可以假装是孩子家长给机构打电话要材料，看看是如何培训的，国外机构是如何培训，最好的私立学校这方面课程是如何设置的。但是未来所有孩子都需要学人工智能吗？机器无法替代的有哪些领域？


假设你的孩子按照现有的信息量，学了人工智能的相关知识，现在长大了，不想读大学，假如他要在这个领域出人头地，有哪些途径？

3.再章：学习了人工智能领域知识的少年，如果不读大学可以干什么？

从商业信息看，最好的企业都在投人工智能哪些方向？他应该去哪些企业？做哪些项目？如果他要创业，该竞争哪些公司？从现有企业信息看，目前人工智能那个方向最火？小公司创业为避免竞争，应该如何选择方向？

从空间的角度，哪些国外已经起来的技术，手段，公司而国内还没有的？也是创业的方向。


拿自己举例，你我的人格特质，适合从事人工智能哪些工作，不适合哪些。或者我们假设一个青年的能力和性格，行业和背景，假如要从事相关行业，自我分析，如何设计转行计划？

4.末章：觉醒前夜

结合上述章节中出现的信息，对近10年的机器觉醒领域做场景的预测：比如从娱乐角度，目前还没有涉及的机器觉醒类母题是哪些？以后有可能会成功的故事点；从生活角度，哪些还没有被涉及的行业或者领域，一旦某个在研的领域有所突破，会带来怎样的改变？

从时间差的角度，学术到商业通常都需要时间来迭代，课程中说是7-8年，我们看2017年或者18年的重点突破，来预测未来的可能方向。比如，从大数据模型走向机器从个案获取信息作出决策。

一项论文或者技术--------》未来有可能突破的实际场景----------------》从事这项工作的人，列举10个，串联前三章。

------------------------------------------

我觉得，信息分析的最核心要素就是降低不确定性，没有必要纠结于那个点那个点，这份报告只要内容够全面，我们写出来能降低普通读者对这个领域的不了解，就是成功的。

我们课程中学到了很多信息收集整理的技巧，借此机会全面的梳理一下，比深入分析一点要好很多。我还是坚持提纲全面比不全面要好，因为实在做不了，可以空着，答辩的时候说留给下一次，但是有还是没有却很关键。

几个调整：

1.从论证点向问题导向调整，建议不要纠结于我们研究什么，就是写一份信息全面充分关于人工智能的报告。面向大家的分析报告，有逻辑不完善的地方，还可以一起讨论完善。比如题目：一小时读懂人工智能。

2.建议维持框架列全，我们完不成可以老实的空着。虽然我觉得可以，因为算上答辩那周，实际上三周的时间来的及。最后完不成的可以借助社区的力量往里面补内容，那些没有写作业的同学，补一些材料我们也会轻松很多。

3.很多东西都是我们作业写过的，只不过方法换了一个场景。

**Comment by wangyin511** [comment]
不要纠结于我们研究什么，就是能降低人工智能信息复杂度的都可以按照一定的组织放进去

**Comment by AphroditeMM** [comment]
昨天看完底特津，也有这个想法，把研究报告按照首章、发展、结尾的结构来成型。正好这个issues提到了，好赞。借大作业来巩固技巧，不论结果如何，过程就是一种收获。

所以，开始动工吧~
