### ISSUE TITLE
序章：人类如何看待人工智能

### ISSUE THREAD

**Issue by wangyin511** [AphroditeMM/I-Robot#9]
> 0.序章：我们如何看待人工智能

底特律的10个问卷，今天最新最好的游戏电影是如何看待人工智能的，历史上的相关作品有哪些，我们可以总结的母题有哪些（比如，物种冲突，人类移情，支持这些母题的）。

这些母题的反元空是哪些？哪几种类型的母题或者题材结合在“机器觉醒”还没有作品存在，而可以去一写的？

既然现在趋势如此，我一个文科生如何和人工智能结合在一起？

**Comment by wangyin511** [comment]
卡片：《底特律：化身为人》的全球问卷

**Comment by wangyin511** [comment]
q1：你会考虑外表像人类的仿生人发展为亲密关系吗？

是65%啊，否17%，不知道18%

**Comment by wangyin511** [comment]
q2：你认为科技会对人造成威胁吗？

是72%，否18%，10%不知道。

**Comment by wangyin511** [comment]
q3：如果您必须生活在荒岛上，只能带一样东西，你选择哪个？

书本15%

手机22%

纸笔21%

游戏机12%

乐器30%

**Comment by wangyin511** [comment]
q4：你认为自己依赖科技吗？

是78%

否15%

不知道7%

**Comment by wangyin511** [comment]
q6:你信神吗？

是36%，否45%，不知道19%

**Comment by wangyin511** [comment]
q5：你最期待那种科技出现？

36%仿生人，飞行车12%，太空旅行19%，脑部链接装置33%

**Comment by wangyin511** [comment]
q7：你会让仿生人照顾小孩吗？

是49%，否24，不知道27%

**Comment by wangyin511** [comment]
q8：你每天花多少时间使用电子产品？
1小时1%
2小时8%
4小时21%
更久65%
不知道5%

**Comment by wangyin511** [comment]
q9：如果你需要紧急手术，你同意让机器执刀吗？
是74%。11%否，15%不知道

**Comment by wangyin511** [comment]
q10：您觉得未来机器可能发展自我意识吗？

是71%，否13%，不知道16%

**Comment by wangyin511** [comment]
q11：你最喜欢的《底特律》角色是谁？

康纳44%

卡拉33%

马库斯23%

**Comment by wangyin511** [comment]
q12：有没有游戏中的场景让你共鸣？

好几次66%

偶尔29%

有一次29%

否3%

**Comment by wangyin511** [comment]
q13：你在《底特律》中最艰难的选择是：

14%让卡拉接受爱丽丝的身份

54%马库斯选择和平或者是暴力

32%让康纳对着克洛伊开枪

**Comment by wangyin511** [comment]
搜狗搜索人工智能电影：16部
http://v.sogou.com/v?query=%C8%CB%B9%A4%D6%C7%C4%DC%B5%E7%D3%B0&class=1&entity=film

**Comment by wangyin511** [comment]
百度搜索人工智能电影：57部
http://v.baidu.com/v?word=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD%E7%94%B5%E5%BD%B1&ct=301989888&rn=67&pn=0&db=0&s=0&fbl=800&ie=utf-8

**Comment by wangyin511** [comment]
豆瓣电影搜索人工智能：

https://movie.douban.com/subject_search?search_text=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD&cat=1002&start=0

**Comment by wangyin511** [comment]
筛选标准：

每个平台得分靠前10名入选，每个电影整理简单的故事模板。

----------------------

这里想和你讨论一点，就是数量的问题。1.影视作品，限定在30个（社会科学中，一般30就能属于正太分布）。2.标准，每个平台按大众评价分数从高到底排列，选三个平台，每个10个？3.还是盯着一个平台收集如豆瓣？因为其他平台如百度，有些没有买版权就是会遗漏，需要多个弥补。

@AphroditeMM

**Comment by wangyin511** [comment]
人工智能小说搜索，知乎：https://www.zhihu.com/question/41407254

《海伯利安》四部曲，《安德的游戏》，《无限异象》，《金色阴影之城》，《2001：太空漫游》，《明天的两面》，《牛顿的觉醒》，《严厉的月亮》，《潘多拉之星》，《神经漫游者》

----------------------------------

如果方便，你再找两个人工智能书单横向对比 @AphroditeMM

**Comment by AphroditeMM** [comment]
人类看待人工智能，态度阵营：
1. 乐观 （底特律问卷调查可以反映部分民意倾向）；
2. 悲观（如霍金，认为AI会终结人类，参见[文章](https://phys.org/news/2014-12-hawking-ai-human.html#inlRlv)）

我认为，在每一次科技革新前都有这么一群「杞人忧天主义者」，但无论任何人出于任何态度，都阻挡不住科技的进步。促使科技进步仿佛是人类的天性。既然人类无法阻挡人工智能的发展步伐，那么我们该怎么应对呢？

报告的态度是积极的，因此我们从小孩子教育捉起，如何在未来人工智能社会游刃有余？

在核心之前，需有两个前提：
1. 人工智能的未来发展预测（序章）
2. 人工智能的当前发展水平（首章）

亦即报告的序章、首章内容。撰写报告时，需贴近这个思路。@ mark提醒自己
